<?php

namespace loginBundle\Repository;

/**
 * logeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logeoRepository extends \Doctrine\ORM\EntityRepository
{
}
