<?php

namespace loginBundle\Repository;

/**
 * loginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class loginRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSessionUser($correo){
		$em = $this->getEntityManager();
		$conn = $em->getConnection();
		$query="
		SELECT e.apellidos, 
	       e.nombres,
	       e.identificacion,
	       e.tipo_identificacion,
	       ud.descripcion_dependencia dependencia
		FROM 
			empleados e ,
			unidades_dependencia ud
		WHERE e.unde_fuerza = 4

		AND e.email_institucional = '".$correo."'

		AND e.unde_fuerza = ud.fuerza
		AND e.unde_consecutivo_laborando = ud.consecutivo
		AND e.unde_fuerza_laborando = ud.fuerza
		";
	$smtp = $conn->prepare($query);
	$smtp->execute();
	return $smtp->fetch();
	// return  $smtp->
	}
}
