matrices_homepage:
    path:     /
    defaults: { _controller: matricesBundle:Default:index }
matriz:
    path:     /matriz/ver
    defaults: { _controller: matricesBundle:Default:getMatriz }

matriz_inserta:
    path:     /matriz/inserta
    defaults: { _controller: matricesBundle:Default:insertMatriz }
