<?php

namespace disanBundle\Repository;

/**
 * disanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class disanRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAptitud($identificacion)
	{
		$em =$this->getEntityManager();
		$db = $em-> getConnection();
 
		$query= "
     SELECT  
      e.identificacion,
      am.numero_acta n_acta,
       am.fecha_acta_medica f_acta,
       am.grad_alfabetico grado ,
       apt.rv_meaning aptitud,
       dis.rv_meaning discapacidad,
       am.disminucion_laboral d_laboral,
       am.disminucion_actual d_actual,
       am.antecedentes,
       crc.rv_meaning i_circustancia,
       ud.descripcion_dependencia unidad,
       s.sigla,
       c.descripcion categoria
       

  FROM empleados e, actas_medicas am , cg_ref_codes crc,unidades_dependencia ud, siglas s, grados g ,categorias c,
  (SELECT dis.rv_low_value, dis.rv_meaning FROM cg_ref_codes dis  WHERE dis.rv_domain ='TIPO DISCAPACIDAD')dis,
   (SELECT apt.rv_low_value, apt.rv_meaning  FROM cg_ref_codes apt   WHERE apt.rv_domain = 'APTITUD SERVICIO') apt
 
 WHERE e.unde_fuerza = 4
   AND e.activo = 'SI'
     
   AND e.consecutivo = am.empl_consecutivo
   AND e.unde_fuerza = am.empl_unde_fuerza
   AND e.unde_consecutivo = am.empl_unde_consecutivo
   AND e.identificacion = ".$identificacion." 
   AND crc.rv_domain = 'TIPO CIRCUNSTANCIA'
   AND am.tipo_circunstancia = crc.rv_low_value 

   AND am.discapacidad = dis.rv_low_value
   AND am.aptitud_servcio = apt.rv_low_value
   
   AND am.unde_consecutivo = ud.consecutivo
   AND am.unde_fuerza = ud.fuerza
   AND ud.id_sigla = s.id_sigla
   
   AND e.grad_alfabetico =  g.alfabetico
   AND e.unde_fuerza     =  g.fuerza
      
   AND g.id_categoria = c.id_categoria
   AND g.fuerza = c.fuerza

   AND am.unde_consecutivo = ud.consecutivo
   AND am.unde_fuerza = ud.fuerza
   AND ud.id_sigla = s.id_sigla
   

   ORDER BY   am.fecha_acta_medica DESC

		";


		$smtp = $db->prepare($query);
		$smtp->execute();
		return $smtp->fetchAll();

		
	}

  public function create_certificacion(
      $id, 
      $aptitud,$retardo,
      $f_retardo,$junta,
      $f_junta,$j_decision ,
      $comite, $f_comite ,
      $c_decision,$tribunal,
      $f_tribunal,$t_decision,
      $observaciones
    ){
    $em = $this->getEntityManager('dbal2');
    $conn = $em->getConnection();
    $insert = $conn->insert('certificacion_fisica', 
          array(
                'identificacion'=> $id,
                'aptitud' => $aptitud,
                'retardo'=> $retardo,
                'f_retardo'=> $f_retardo,
                'junta_medica_laboral'=> $junta,
                'f_junta'=> $f_junta,
                'decision_junta'=> $j_decision,
                'comite_laboral'=>$comite,
                'f_comite'=>$f_comite,
                'decision_comite'=>  $c_decision,
                'tribunal_medico'=> $tribunal,
                'f_tribunal'=> $f_tribunal,
                'decision_tribunal'=> $t_decision,
                'observaciones'   => $observaciones,
            ));
  }
  public function getCertificacion($id){
    $em = $this->getEntityManager('dbal2');
    $conn = $em->getConnection();
    $query = "
           SELECT * 
           FROM `certificacion_fisica`
            WHERE `identificacion` = ".$id."
          ";

    $smtp=$conn->prepare($query);

    $smtp->execute();
    return $smtp->fetchAll();
  }

  public function getEstadoSalud($id){
    $em = $this->getEntityManager();
    $conn = $em->getConnection();
    $query = "
            SELECT crc.rv_meaning estado,
             esp.descripcion,
             esp.numero_disposicion,
             esp.fecha_disposicion,
             esp.fecha_inicio

        FROM estados_salud_empl esp,
         escalafones_empleados ee ,
         cg_ref_codes crc 
        WHERE ee.fuerza_empleado = 4
        AND   ee.id_empleado     = esp.empl_consecutivo
        AND   ee.fuerza_empleado      = esp.empl_unde_fuerza
        AND   ee.unde_consecutivo = esp.empl_unde_consecutivo
        AND   crc.rv_domain = 'TIPO SALUD'
        AND   esp.tipo_salud = crc.rv_low_value
             
        AND ee.identificacion = ".$id."
    ";

    $smtp=$conn->prepare($query);

    $smtp->execute();
    return $smtp->fetchAll();

  }




}


