<?php

namespace jpmBundle\Repository;

/**
 * jpmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jpmRepository extends \Doctrine\ORM\EntityRepository
{

	public function getSanciones($identificacion){
		global $em,$db;
		$GLOBALS['em'] = $this->getEntityManager();
		$GLOBALS['db'] = $em->getConnection();
		$query = "
         	SELECT
         		se.id_fechfisc_sancion fecha_sancion,
				tn.descripcion Tipo_Novedad,
				cn.descripcion Clase_Novedad,
				se.numero_expediente num_exped,
				se.motivo_hechos,
				se.numero_disposicion num_dispo,
				d.descripcion disposicion,
				SE.GRAD_ALFABETICO grado_novedad
          	FROM
				empleados           e,
				sanciones_empleados se,
				clases_novedades    cn,
				tipos_novedades     tn,
				disposiciones d
         	WHERE
         		e.unde_fuerza = 4
				AND e.consecutivo 			= se.empl_consecutivo
				AND e.unde_fuerza 			= se.empl_unde_fuerza
				AND e.identificacion 		= ".$identificacion."
				AND se.id_clase_novedad 	= cn.id_clase_novedad
				AND tn.id_tipo_novedad 		= cn.id_tipo_novedad
				AND se.disp_id_disposicion 	= d.id_disposicion
   ";
	   	$smtp = $GLOBALS['db']->prepare($query);
	   	$smtp->execute();
	   	return $smtp->fetchAll();
	}
	public function getInvestigaciones($identificacion){
		$query = "
			SELECT
				ie.fecha_inicio,
				ie.fecha_hechos,
				ie.numero_proceso,
				ie.observacion,
				tipo_inves.rv_abbreviation tipo_inves
			FROM
				empleados                 e,
				investigaciones_empleados ie,
				cg_ref_codes              tipo_inves

			WHERE 	e.unde_fuerza 			= 4
				AND e.activo 				= 'SI'
				AND e.consecutivo 			= ie.empl_consecutivo
				AND e.unde_fuerza 			= ie.empl_unde_fuerza
				AND e.unde_consecutivo 		= ie.empl_unde_consecutivo
				AND e.identificacion 		= ".$identificacion."
				AND tipo_inves.rv_domain 	= 'TIPO SUSPENSION'
				AND ie.tipo_investigacion 	= tipo_inves.rv_low_value
		";
		$smtp = $GLOBALS['db']->prepare($query);
	   	$smtp->execute();
	   	return $smtp->fetchAll();
	}
	public function getSuspenciones($identificacion){
		$query = "
			SELECT
				sue.numero_disposicion num_disposicion,
				d.descripcion disposicion,
				sue.fecha_disposicion,
				sue.numero_expediente,
				sue.id_fechfisc_suspension fecha_suspencion,
				sue.fecha_termino,
				sue.numero_dias || '-' || sue.numero_meses ||'-' || sue.numero_anos dias_mes_año,
				cn.descripcion clase_novedad,
				ref_cod.rv_meaning Tipo_suspencion
			FROM
				empleados e,
				suspensiones_empleados sue,
				cg_ref_codes ref_cod, clases_novedades cn,
				disposiciones d
			WHERE
				e.unde_fuerza = 4
			AND e.activo = 'SI'
			AND e.identificacion = ".$identificacion."
			AND e.consecutivo = sue.empl_consecutivo
			AND e.unde_fuerza = sue.empl_unde_fuerza
			AND e.unde_consecutivo = sue.empl_unde_consecutivo

			AND ref_cod.rv_domain = 'TIPO SUSPENSION'
			AND sue.tipo_suspension  = ref_cod.rv_low_value
			AND sue.id_clase_novedad = cn.id_clase_novedad
			AND sue.disp_id_disposicion = d.id_disposicion
		";
			$smtp = $GLOBALS['db']->prepare($query);
	   	$smtp->execute();
	   	return $smtp->fetchAll();

	}
	public function getSeparaciones($identificacion){
		$query = "
		SELECT
	 se.id_fechfisc_separacion  AS fecha_separacion,
	 sue.id_fechfisc_suspension AS fecha_suspencion,
	 t_susp.rv_meaning          AS tipo_suspension,
	 cn.descripcion             AS novedad,
	 d.descripcion              AS disposicion,
	 se.numero_disposicion      AS num_dispo_se,
	 se.fecha_disposicion,
	 se.fecha_presentacion,
	 se.anos_pena,
	 se.meses_pena,
	 se.dias_pena,
	 tc.rv_meaning              AS tipo_condena,
	 t_recurso.rv_meaning       AS tipo_recurso,
	 t_solucion.rv_meaning      AS tipo_solucion,
	 cn_suspension.descripcion AS novedad_suspension
FROM empleados e,separaciones_empleados se
JOIN cg_ref_codes tc
ON (se.tipo_condena = tc.rv_low_value)
JOIN cg_ref_codes t_recurso
ON (se.tipo_recurso = t_recurso.rv_low_value)
JOIN cg_ref_codes t_solucion
ON (se.tipo_solucion = t_solucion.rv_low_value)
JOIN clases_novedades cn
USING (id_clase_novedad)
JOIN disposiciones d
ON se.disp_id_disposicion = d.id_disposicion
JOIN suspensiones_empleados sue
USING (id_susp_empl)
JOIN cg_ref_codes t_susp
ON (sue.tipo_suspension = t_susp.rv_low_value)
JOIN clases_novedades cn_suspension
ON (sue.id_clase_novedad = cn_suspension.id_clase_novedad)


WHERE e.unde_fuerza = 4
AND e.identificacion = ".$identificacion."
AND e.consecutivo = se.empl_consecutivo
AND e.unde_fuerza = se.empl_unde_fuerza
AND e.unde_consecutivo = se.empl_unde_consecutivo

AND tc.rv_domain = 'TIPO CONDENA'
AND t_recurso.rv_domain = 'TIPO RECURSO'
AND t_solucion.rv_domain = 'TIPO SOLUCION'
AND t_susp.rv_domain = 'TIPO SUSPENSION'
		";
		$smtp = $GLOBALS['db']->prepare($query);
		$smtp->execute();
		return $smtp->fetchAll();


	}

}
