<?php

namespace matricesBundle\Repository;

/**
 * matrizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matrizRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMatriz(){
		$em =$this->getEntityManager('dbal2');
		$conn = $em->getConnection();
		$query = "
				SELECT * 
				FROM `matriz`
			";
		$smtp = $conn->prepare($query);
		$smtp->execute();
		return $smtp->fetch(); 
	}
	public function getIndicadores($id){
		$em =$this->getEntityManager('dbal2');
		$conn = $em->getConnection();
		$query = "
			SELECT DISTINCT `mi`.`descripcion`,`mv`.`estado`
			FROM `matriz_validacion` AS `mv`,
			     `matriz_indicadores` AS `mi`
			WHERE `mv`.`id_indicador` = `mi`.`id_indicador`
			AND   `mv`.`id_matriz` = ".$id."
		";
		$smtp = $conn->prepare($query);
		$smtp->execute();
		return $smtp->fetchAll(); 

	}
	public function getParametros($id){
		$em =$this->getEntityManager('dbal2');
		$conn = $em->getConnection();
		$query = "
			SELECT `mv`.`parametro` ,`mv`.`parametro_valor`,
					`mv`.`tipo_requisito`,`mv`.`requisito`
			FROM `matriz_validacion` AS `mv`,
			     `matriz_indicadores` AS `mi`
			WHERE `mv`.`id_indicador` = `mi`.`id_indicador`
			AND   `mv`.`id_matriz` = ".$id."

		";
		$smtp = $conn->prepare($query);
		$smtp->execute();
		return $smtp->fetchAll();

	}

	public function updateEstado($id_matriz,$id_indicador,$estado){
		$em =$this->getEntityManager('dbal2');
		$conn = $em->getConnection();
		


	}

}
