<?php

namespace ldapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ldapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ldapRepository extends \Doctrine\ORM\EntityRepository
{
}
